name: Build Main

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.0.x, 14.x, 15.x, 16.0.x, 16.x, 17.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install --ignore-scripts

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm test
